gameCollection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('gameCollections.urls')),

]

gameCollections/urls.py
from django.urls import path
from . import views

app_name = 'gameCollections'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('gameCollections/', views.genres, name = 'genres'),
    path('<int:genre_id>/games/', views.games, name = 'games'),

    path('new_genre/', views.new_genre, name = 'new_genre'),
    path('new_game/<int:genre_id>/', views.new_game, name='new_game'),
    path('edit_game/<int:game_id>/', views.edit_game, name='edit_game'),
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
     # Include default auth urls.
     path('', include('django.contrib.auth.urls')),

     path('register/', views.register, name = 'register'),
]     

gameCollections/models.py
from django.db import models
from django.contrib.auth.models import User

class Genre(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Game(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    console = models.CharField(max_length=200)
    releaseDate = models.DateField()
 
    class Meta:
        verbose_name_plural = 'games'

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

gameCollections/forms.py
from django import forms
from .models import Genre, Game

class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name']
        labels = {'name': ''}

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'console', 'releaseDate']
        labels = {'name': 'Game', 'console': 'Console', 'releaseDate': 'Realease Date' }

gameCollections/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Genre, Game
from .forms import GenreForm, GameForm

def index(request):
        return render(request, 'gameCollections/index.html')

@login_required
def genres(request):
    genres = Genre.objects.filter(owner=request.user).order_by('name')
    context = {'genres' : genres}
    return render (request, 'gameCollections/genres.html', context)

@login_required
def games(request, genre_id):
    genre = Genre.objects.get(id = genre_id)

    if genre.owner != request.user:
        raise Http404

    games = genre.game_set.order_by('-releaseDate')
    context = {'genre' : genre, 'games' : games}
    return render (request, 'gameCollections/games.html', context)

@login_required
def new_genre(request):
    """Add a new genre."""
    if request.method != 'POST':
        form = GenreForm()

    else:
        form = GenreForm(data=request.POST)
        if form.is_valid():
            new_genre = form.save(commit=False)
            new_genre.owner = request.user
            new_genre.save()
            return redirect('gameCollections:genres')

    context = {'form': form}
    return render(request, 'gameCollections/new_genre.html', context)

@login_required
def new_game(request, genre_id):
    """Add a new game for a particular genre."""
    genre = Genre.objects.get(id=genre_id)
 
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = GameForm()
    else:
        # POST data submitted; process data.
        form = GameForm(data=request.POST)
        if form.is_valid():
            new_game = form.save(commit=False)
            new_game.genre = genre
            new_game.save()
            return redirect('gameCollections:games', genre_id=genre_id)
    # Display a blank or invalid form.
    context = {'genre': genre, 'form': form}
    return render(request, 'gameCollections/new_game.html', context)

@login_required
def edit_game(request, game_id):
    """Edit an existing Game."""
    game = Game.objects.get(id=game_id)
    genre = game.genre 
    if genre.owner != request.user:
        raise Http404
 
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = GameForm(instance=game)
    else:
        # POST data submitted; process data.
        form = GameForm(instance=game, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('gameCollections:games', genre_id=genre.id)
    context = {'game': game, 'genre': genre, 'form': form}
    return render(request, 'gameCollections/edit_game.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form. 
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
 
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('gameCollections:index')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

gameCollections/templates/gameCollections/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Game Collection</title>
      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'gameCollections:index'%}">Game Collection</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gameCollections:genres'%}"> Genres </a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

gameCollections/templates/gameCollections/edit_game.html
{% extends "gameCollections/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h3> Edit {{ game.name }} for <a href="{% url 'gameCollections:games' genre.id %}">{{ genre }}</a></h3>
{% endblock page_header %}

{% block content %}
    
 
    <form input="{% url 'gameCollections:edit_game' game.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class= "btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

gameCollections/templates/gameCollections/games.html
{% extends "gameCollections/base.html" %}

{% block page_header %}
    <h3>{{ genre }}</h3>
{% endblock page_header %}

{% block content %}
    
    <h3><a class="btn btn-lg btn-primary" href="{% url 'gameCollections:new_game' genre.id %}" role="button">Add new Game</a></h3>
    
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Game</th>
                <th scope="col">Console</th>
                <th scope="col">Release Date</th>
                <th scope="col"></th>
            <tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <th>{{ game.name }}</th>
                <th>{{ game.console }}</th>
                <th>{{ game.releaseDate }}</th>
                <th><a class="btn btn-lg btn-primary" href="{% url 'gameCollections:edit_game' game.id %}" role="button">Edit Game</a></th>

            </tr>
        {% empty %}
            <p>No games have been added yet.</p>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

gameCollections/templates/gameCollections/genres.html
{% extends "gameCollections/base.html" %}

{% block content %}

    <h3><a class="btn btn-lg btn-primary" href="{% url 'gameCollections:new_genre' %}" role="button">Add a new Genre</a></h3>
    
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col"><h1>Genres</h1></th>
            <tr>
        </thead>
        <tbody>
        {% for genre in genres %}
            <tr>
                <th><a href="{% url 'gameCollections:games' genre.id %}">{{ genre }}</a></th>
            </tr>
        {% empty %}
            <h3>No genres have been added yet.</h3>
        {% endfor %}
        </tbody>
        
    </table>

    

{% endblock content %}

gameCollections/templates/gameCollections/index.html
{% extends "gameCollections/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Document your Game Collection</h1>
        <p class="lead">Game Collection is an app that allows you to keep track of all your games. 
        Organized by genre you can have a collection of as many games as you want. 
        You can also store what console the game is for and its release date.</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

gameCollections/templates/gameCollections/new_game.html
{% extends "gameCollections/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new game for <a href="{% url 'gameCollections:games' genre.id %}">{{ genre }}</a></h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'gameCollections:new_game' genre.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class= "btn btn-primary">Add Game</button>
        {% endbuttons %}
    </form>
 
{% endblock content %}

gameCollections/templates/gameCollections/new_genre.html
{% extends "gameCollections/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new Genre:</h2>
{% endblock page_header %}

{% block content %}
 
    <form action="{% url 'gameCollections:new_genre' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class= "btn btn-primary">Add Genre</button>
        {% endbuttons %}
    </form>
 
{% endblock content %}